### ISSUE TITLE
Export/Import CD settings

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#79] opened 2014-09-30 12:34 UTC
We're getting to have a lot of settings by now. It would be amazing to offer an export/import feature where webmasters could export their settings including display, menus, icons, webmaster, widgets, etc.

**Comment by joelworsham** [comment] 2018-09-07 17:50
This is HUGE. People want this so bad.

I think it's a pro option personally. Let's DO IT.

**Comment by d4mation** [comment] 2018-10-11 00:29
Turns out I made a duplicate of this in #159, but there's more details there so I'm going to close this one in favor of it. Sorry 🤐

**Closed by d4mation** 2018-10-11 00:29 UTC
Labels: enhancement, next build, pro
